server:
  port: 9531

spring:
  application:
    name: service-obsidian-client
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: {"defaultZone": "http://localhost:9527/eureka/"}
